// todo2/src/client/home.tsx
import React, { useState, useEffect } from "react";
import TodoList from "./Home/TodoList";
import TodoDialog from "./Home/DialogComponent";
import axios from "axios";

const App = () => {
  const [todos, setTodos] = useState([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingTodo, setEditingTodo] = useState(null);

  // 初期データ取得
  useEffect(() => {
    axios.get("http://localhost:3000/api/todos").then((response) => {
      setTodos(response.data);
    });
  }, []);

  // 検索機能
  const handleSearch = () => {
    axios
      .get(`http://localhost:3000/api/todos/search?query=${searchQuery}`)
      .then((response) => {
        setTodos(response.data);
      });
  };

  return (
    <div className="p-6 bg-gray-100 min-h-screen">
      <h1 className="text-2xl font-bold mb-6">TODO App</h1>
      <div className="mb-4 flex gap-2">
        <input
          type="text"
          className="border p-2 flex-1 rounded-md"
          placeholder="Search TODOs..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
        />
        <button
          onClick={handleSearch}
          className="bg-blue-500 text-white px-4 py-2 rounded-md"
        >
          Search
        </button>
      </div>
      <button
        onClick={() => {
          setEditingTodo(null);
          setIsDialogOpen(true);
        }}
        className="bg-green-500 text-white px-4 py-2 rounded-md mb-4"
      >
        Add TODO
      </button>
      <TodoList
        todos={todos}
        setTodos={setTodos}
        onEdit={(todo) => {
          setEditingTodo(todo);
          setIsDialogOpen(true);
          console.log("#home.onEdit");
          console.log(todo);
        }}
      />
      {isDialogOpen && (
        <TodoDialog
          setTodos={setTodos}
          editingTodo={editingTodo}
          onClose={() => setIsDialogOpen(false)}
        />
      )}
    </div>
  );
};

export default App;

// vue_todo1/src/client/Home.vue
<template>
  <div class="container mx-auto p-4">
    <h1 class="text-2xl font-bold mb-4">TODO App</h1>
    <SearchBar @search="searchTodos" />
    <button
      class="bg-blue-500 text-white px-4 py-2 rounded mb-4"
      @click="openDialog('add')"
    >
      Add TODO
    </button>
    <TodoList
      :todos="todos"
      @edit="openDialog('edit', $event)"
      @delete="deleteTodo"
    />
    <TodoDialog
      v-if="showDialog"
      :mode="dialogMode"
      :currentTodo="currentTodo"
      @close="closeDialog"
      @save="saveTodo"
    />
  </div>
</template>

<script>
import { ref } from "vue";
import TodoList from "./Home/TodoList.vue";
import TodoDialog from "./Home/TodoDialog.vue";
import SearchBar from "./Home/SearchBar.vue";
import axios from "axios";

export default {
  components: { TodoList, TodoDialog, SearchBar },
  setup() {
    const todos = ref([]);
    const showDialog = ref(false);
    const dialogMode = ref("add");
    const currentTodo = ref(null);

    const fetchTodos = async () => {
      const response = await axios.get("/api/todos");
      console.log(response.data);
      todos.value = response.data;
    };

    const searchTodos = async (query) => {
      const response = await axios.get(`/api/todos?search=${query}`);
      todos.value = response.data;
    };

    const openDialog = (mode, todo = null) => {
      dialogMode.value = mode;
      currentTodo.value = todo;
      showDialog.value = true;
    };

    const closeDialog = () => {
      showDialog.value = false;
      currentTodo.value = null;
    };

    const saveTodo = async (todo) => {
      if (dialogMode.value === "add") {
        await axios.post("/api/todos", todo);
      } else {
        await axios.put(`/api/todos/${todo.id}`, todo);
      }
      fetchTodos();
      closeDialog();
    };

    const deleteTodo = async (id) => {
      try{  
        console.log("deleteTodo=", id);
        await axios.delete(`/api/todos/${id}`);
        fetchTodos();
      } catch (error) {
        console.error('Failed to fetch todos:', error);
      }
    };

    fetchTodos();

    return {
      todos,
      showDialog,
      dialogMode,
      currentTodo,
      openDialog,
      closeDialog,
      saveTodo,
      searchTodos,
      deleteTodo,
    };
  },
};
</script>
